Hw04
Flibora/test_repository pull request #2
Opened 2021-10-16 22:15 UTC by Flibora

06-011

2021-10-17 18:45 UTC, nafanya-90 requested changes

2021-10-17 18:45 UTC, nafanya-90 commented on hw04/1.py
> +str = input ()
не должно быть пробела перед скобкой при вызове функции

2021-10-17 18:45 UTC, nafanya-90 commented on hw04/10.py
> +    a[i] *= -2
по заданию нужно создать новый список, а не изменить исходный

2021-10-17 18:45 UTC, nafanya-90 commented on hw04/10.py
> +    if i == lenght:
Для чего тут условие в цикле?

2021-10-17 18:45 UTC, nafanya-90 commented on hw04/12.py
> +print(a)
Задание выполнено не верно. В результате должен измениться текущий словарь соотвествии с описанным алгоритмом. Результирующий вид словаря `а` должен быть такой:

{'test4': 'test_value', 'europe6': 'eur', 'dollar6': 'usd', 'ruble5': 'rub'}

2021-10-17 18:45 UTC, nafanya-90 commented on hw04/13.py
> +lenght_a =len(spisok_a)
После оператора `=` ставится пробел

2021-10-17 18:45 UTC, nafanya-90 commented on hw04/2.py
> +str = input ()
не должно быть пробела перед скобкой при вызове функции

2021-10-17 18:45 UTC, nafanya-90 commented on hw04/2.py
> +new_str = str[len - 2]
Для получения символов строки с конца не нужно знать длину этой строки - достаточно просто обращаться к элементам с отрицательным индексом, например `str[-2]`

2021-10-17 18:45 UTC, nafanya-90 commented on hw04/3.py
> +new_str = str[ :5]
При использовании операторов среза они не оборачиваются пробелами

2021-10-17 18:45 UTC, nafanya-90 commented on hw04/4.py
> +new_str = str[ :len - 2]
Для получения символов строки с конца не нужно знать длину этой строки - достаточно просто обращаться к элементам с отрицательным индексом

2021-10-17 18:45 UTC, nafanya-90 commented on hw04/5.py
> +new_str = str[ 1: : 2]
Не верно. Нужно получить символы `0,2,4,6...`, а результат работы программы символы `1,3,5,7...`

2021-10-17 18:45 UTC, nafanya-90 commented on hw04/7.py
> +if family >50:
Оператор сравнения оборачивается пробелами

2021-10-17 18:45 UTC, nafanya-90 commented on hw04/7.py
> +family = int(input())
Имя переменной должно отражать ее содержимое. В переменной явно хранится некое число, а по названию кажется, что там будет что-то типа словаря или списка с данными.

2021-10-17 18:45 UTC, nafanya-90 commented on hw04/7.py
> +elif 50 <= family >= 20:
Условие не верное. В таком виде оно не выполнится никогда.

2021-10-17 18:45 UTC, nafanya-90 commented on hw04/8.py
> +    print( stroka + "!!!")
Внутри вызова функции пробел после скобки не ставится

2021-10-17 18:45 UTC, nafanya-90 commented on hw04/9.py
> +    print(stroka[1: -1])
При использовании операторов среза они не оборачиваются пробелам

2021-10-18 09:12 UTC, nafanya-90 requested changes

2021-10-18 09:12 UTC, nafanya-90 commented on hw04/10.py
> +new_a = [None] * 5
Тут не нужен предзаполненный None список. Во первых, потому что это занимает память, а во вторых потому, что у тебя задано строго 5, а если в исходном списке `a` изменится количество элементов?

Тут нужно создать просто пустой список.

2021-10-18 09:12 UTC, nafanya-90 commented on hw04/10.py
> +    new_a[i] = a[i] * -2
Затем в цикле на каждой итерации добавлять в него новый элемент в соотсевии с условием задачи. https://www.programiz.com/python-programming/methods/list/append

2021-10-18 09:12 UTC, nafanya-90 commented on hw04/12.py
> +print(a)
Алгоритм следующий:
1. Нужно обойти циклом все ключи исходного словаря `a`;
2. На каждой итерации цикла:
a. получить длину текущего ключа; например длина ключа `test` = `4`;
b. создать новый элемент словаря с ключем, равным текущему ключу + длина этого ключа и значением, соотвествующим текущему значению ключа. Например: текущий ключ `test`. Его длина: `4`. Значение текущего ключа: `test_value`; Нужно создать в словаре новый элемент равный `test4: test_value`.
c. удалить из словаря элемент с текущим ключем. Т.е. удалить элемент `a['test']`;

2021-10-18 09:12 UTC, nafanya-90 commented on hw04/14.py
> +list =[1] * 15
Не используй в качестве имен переменных зарезервированные слова. Типа list, dict, set etc. Это может привести к проблемам идентификации имен

2021-10-18 09:12 UTC, nafanya-90 commented on hw04/14.py
> +list =[1] * 15
Для чего тут предзаполненный список из 15 элементов? Нужно создать список, содержащий только первых два константных значения: 1, 1. Остальные элементы добавлять в конец списка по тому же самому принципу. Только условие цикла будет зависеть не от длины предзаполненного списка, а от ожидаемого количества элементов.

2021-10-18 09:12 UTC, nafanya-90 commented on hw04/2.py
> +new_str = str[- 2]
В унарных операция после минуса пробел не ставится

2021-10-18 09:12 UTC, nafanya-90 commented on hw04/3.py
> +new_str = str[ :5]
Перед двоеточием не должно быть пробела

2021-10-18 09:12 UTC, nafanya-90 commented on hw04/4.py
> +new_str = str[ :- 2]
Не должно быть пробела перед двоеточием и после минуса

2021-10-18 09:12 UTC, nafanya-90 commented on hw04/5.py
> +new_str = str[ 0: : 2]
В срезах не должно быть пробелов.

2021-10-18 09:12 UTC, nafanya-90 commented on hw04/7.py
> +elif (number_family >= 20 and number_family <= 50):
Условие можно заменить на более короткое, без оператора and: `20 <= number_family <= 50`

2021-10-19 08:54 UTC, Flibora commented on hw04/14.py
> +list =[1] * 15
переделал под немного дргое условие

2021-10-19 10:42 UTC, nafanya-90 approved these changes

2022-12-19 00:02 UTC, closed without merging